config/routes.rb
Rails.application.routes.draw do
  resources :hooks

  resources :bugs

  resources :comments

  resources :submodules

  resources :employees

  resources :projects

  devise_for :users
  root 'projects#index'
  get 'projects/:id/submodules/'=>"projects#submodules",:as=>"project_modules"
  get 'team/projects/:id'=>"projects#team",:as=>"project_team"
  get 'team/:id'=>"projects#fullteam",:as=>"full_team"
  post 'team/add'=>"projects#add_to_team"
  get 'submodules/projects/:id'=>"submodules#new",:as=>"new_submodule_for_project"
  get 'comments/new/:id'=>"comments#new",:as=>"new_comment_for_submodule"  
  get 'submodules/bug/:id'=>"submodules#bug",:as=>"bugs_in_submodule"
  get 'bugs/new/:submodule_id'=>"bugs#new",:as=>"new_bug_for_submodule"
  get 'projects/complete/:id'=>"projects#complete",:as=>"complete_story"
  put 'request/bugs/:submodule_id/:bug_token'=>"bugs#make_bug"
end

app/models/employee.rb
class Employee < ActiveRecord::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @employees = Employee.all
    respond_with(@employees)
  end

  def show
    respond_with(@employee)
  end

  def new
    @employee = Employee.new
    respond_with(@employee)
  end

  def edit
  end

  def create
    @employee = Employee.new(employee_params)
    @employee.save
    respond_with(@employee)
  end

  def update
    @employee.update(employee_params)
    respond_with(@employee)
  end

  def destroy
    @employee.destroy
    respond_with(@employee)
  end

  private
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:name, :area, :proficiency, :available)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :area %><br>
    <%= f.text_area :area %>
  </div>
  <div class="field">
    <%= f.label :proficiency %><br>
    <%= f.text_field :proficiency %>
  </div>
  <div class="field">
    <%= f.label :available %><br>
    <%= f.check_box :available %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Area</th>
      <th>Proficiency</th>
      <th>Available</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.area %></td>
        <td><%= employee.proficiency %></td>
        <td><%= employee.available %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Area:</strong>
  <%= @employee.area %>
</p>

<p>
  <strong>Proficiency:</strong>
  <%= @employee.proficiency %>
</p>

<p>
  <strong>Available:</strong>
  <%= @employee.available %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>