config/routes.rb
Rails.application.routes.draw do
  resources :hooks

  resources :bugs

  resources :comments

  resources :submodules

  resources :employees

  resources :projects

  devise_for :users
  root 'projects#index'
  get 'projects/:id/submodules/'=>"projects#submodules",:as=>"project_modules"
  get 'team/projects/:id'=>"projects#team",:as=>"project_team"
  get 'team/:id'=>"projects#fullteam",:as=>"full_team"
  post 'team/add'=>"projects#add_to_team"
  get 'submodules/projects/:id'=>"submodules#new",:as=>"new_submodule_for_project"
  get 'comments/new/:id'=>"comments#new",:as=>"new_comment_for_submodule"  
  get 'submodules/bug/:id'=>"submodules#bug",:as=>"bugs_in_submodule"
  get 'bugs/new/:submodule_id'=>"bugs#new",:as=>"new_bug_for_submodule"
  get 'projects/complete/:id'=>"projects#complete",:as=>"complete_story"
  put 'request/bugs/:submodule_id/:bug_token'=>"bugs#make_bug"
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :submodules
  validates :desc,presence:true
  validates :title,presence:true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy,:complete]
  after_action :send_mail,only:[:update]
  respond_to :html

  def index
    if user_signed_in?
      @projects = Project.all
      respond_with(@projects)
    else
      redirect_to new_user_session_path
    end
  end

  def show
    respond_with(@project)
  end

  def new
    @project = Project.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to root_path
    else
      respond_with(@project)
    end
  end

  def update
    if @project.update(project_params)
      redirect_to root_path
    else
      respond_with(@project)
    end
  end

  def destroy
    @project.destroy
    respond_with(@project)
  end
  def submodules
    @project_id=params[:id]
    @submodules=Submodule.where(:project_id=>params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end
  def team
    @@project_id=params[:id]
  end
  def fullteam
    puts params[:id]
    @users=User.with_role params[:id]
  end
  def add_to_team
    if user_signed_in? and current_user.has_role?"admin"
      teammate=User.where(:email=>params[:project][:member]).first
      @project=Project.find(@@project_id)
      if teammate==nil
        flash[:alert]="User not found"
        redirect_to root_path
      else
        teammate.add_role @project.id.to_s
        flash[:notice]="User added"
        redirect_to root_path
      end
    else
      flash[:alert]="Watch your step"
      redirect_to root_path
    end 

  end
  def send_mail()
    UpdateNotifier.send_update(@project).deliver
  end
  private
  def set_project
    if user_signed_in?
      @project = Project.find(params[:id])
    else
      redirect_to new_user_session_path
    end
  end

  def project_params
    params.require(:project).permit(:title, :desc)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
         <div id="error_explanation">
          <div class="alert alert-danger">  <%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:
         <ul>
         <% @project.errors.full_messages.each do |message| %>
           <li><%= message %></li>
         <% end %>
         </ul>
         </div>
         </div>
       <% end %>
       <div class="form-group">
       <%= f.label :title %><br>
       <%= f.text_field :title,:class=>"form-control input-md" %>
       </div>
       <div class="field">
       <%= f.label :desc %><br>
       <%= f.text_area :desc,:class=>"form-control input-md",:id=>"desc"%>
       </div>
       <div class="actions">
         <br>
         <button type="submit" class="btn btn-success">
             <i class="fa fa-save"></i> Save
           </button>
           <a class="btn btn-danger"  href="/"><i class="fa fa-trash-o"></i> Cancel</a>
 </div>
<% end %>
<script>
$(document).ready(function(){
    $("#desc").jqte();
    })
</script>

app/views/projects/_submodules.html.erb
<div class="row">
  <%=link_to new_submodule_for_project_path(@project_id),:class=>"pull-right btn btn-primary",:remote=>"true" do%>
   <i class="fa fa-plus-circle"></i> New user story
  <%end%>
</div>
<br>
<div class="row">
<%if @submodules.count==0%>
  <div class="warn">No submodules found</div>
<%else%>
  <%@submodules.each do |submodule|%>
    <% if submodule.deadline < Date.today  or submodule.close==true%>
      <div class="red modules">
      <%else%>
        <div class="modules">
      <%end%>
    <div class="module_name"><%=submodule.name.titlecase%><div class="deadline"><%=submodule.deadline%></div></div>
  <div class="module_desc"><%=submodule.desc.html_safe%></div>
  <br>
  <div class="module_name">Thoughts</div>
  <br><br>
  <%if submodule.comments.count==0%>
    <div class="text-center">No thoughts</div>
  <%end%>
  <%submodule.comments.each do |comment|%>
    <div class="single_comments"> 
      <div class="comment_user"><u><%=gravatar_image_tag(comment.comment_owner,:class=>"img-circle profile-img",:size=>8)%><%=comment.comment_owner%></u> says </div>
      <div class="comment_content"><%=comment.content.html_safe%></div>
    </div>

    <br>
  <%end%>
  <br>
  <%=link_to edit_submodule_path(submodule),:class=>"btn btn-info",:remote=>true  do%>
   <i class="fa fa-edit"></i> Edit Story
  <%end%>
  <%=link_to bugs_in_submodule_path(submodule.id),:class=>"btn btn-info",:remote=>true do%>
  <i class="fa fa-bug"></i> <%=submodule.bugs.count.to_s+" Bugs"%>
  <%end%>
  <%=link_to new_comment_for_submodule_path(submodule.id),:class=>"btn btn-success",:remote=>"true" do%>
   <i class="fa fa-comments"></i> New comment
  <%end%>

  <div id="bugs"></div>
</div>
<br>
<br>
<br>
<%end%>
<%end%>
</div>

app/views/projects/complete.html.erb
<div class="row">
  <%=@project.id%>
  <%=@project.title%>
  <ul class="nav nav-tabs">
    <li role="presentation"><a href="#">Project overview</a></li>
    <li role="presentation"><a href="#">Stories</a></li>
    <li role="presentation"><a href="#">Bugs</a></li>
    <li role="presentation"><a href="#">Team</a></li>
  </ul>
</div>
<div id="overview">
  <div class="lead">  <%=@project.title%></div>
  <div class="description"><%=@project.desc.html_safe%></div>
</div>
<div id="stories">
  <b>Stories</b><br>
  Total stories <%=@project.submodules.count%><br>
<%@project.submodules.each do |submodule|%>
  <%=submodule.name%>
  <%=submodule.desc%>
  <br>
<%end%>
</div>
<div id="bugs">
</div>
<div id="team">
</div>
</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

app/views/projects/fullteam.html.erb
<h2>Team Members</h2>
<%@users.each do |user|%>
  <%=gravatar_image_tag(user.email,:class=>"img-circle profile-img")%>  <%=user.email%>
<%end%>

app/views/projects/index.html.erb
<div class="row">

  <%= link_to new_project_path,:class=>"btn btn-primary pull-right",:remote=>"true" do%>
    <i class="fa fa-plus-circle"></i>  New Iteration
  <%end%>
</div>
<div class="row">
  <h1>Iterations</h1>
</div>      
<%if @projects.count==0%>
  <div class="warn">No iterations found</div>
<%else%>
<% @projects.each do |project| %>
  <div class="row">
    <div class="module_name"><%= project.title %></div><br>
    <div  class="module_desc"><%= project.desc.html_safe %></div>
    <br>
    <%= link_to edit_project_path(project),:class=>"btn btn-info",:remote=>"true"  do%>
      <i class="fa fa-edit"></i> Edit
    <%end%>   
    <%=link_to  project_modules_path(project.id),:class=>"btn btn-warning",:remote=>"true" do%>
             <i class="fa fa-book"></i> <%=project.submodules.count.to_s+" User stories"%>
         <%end%>
         <%=link_to full_team_path(project.id),:class=>"btn btn-primary" do%>
           <i class="fa fa-user"></i> Team
         <%end%> 
    <%= link_to  project, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-danger" do%>
      <i class="fa fa-trash-o"></i> Destroy
    <%end%>

  </div>
<% end %>
<br>
    <div id="submodules"></div>
  <% end %>
</div>

app/views/projects/new.html.erb
<h3>Create iterations</h3>

<%= render 'form' %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @project.desc %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/projects/submodules.html.erb
<div class="row">
  <%=link_to "New user story",new_submodule_for_project_path(@project_id),:class=>"pull-right btn btn-primary"%>
</div>
<br>
<div class="row">
<%if @submodules.count==0%>
  <div class="warn">No submodules found</div>
<%else%>
<%@submodules.each do |submodule|%>
  <div class="modules">
  <p class="module_name"><%=submodule.name.titlecase%></p><br>
  <p class="module_desc"><%=submodule.desc%></p><br>
  <br>
  <div class="module_name">Thoughts</div>
  <br><br>
  <%if submodule.comments.count==0%>
    <p class="text-center">No thoughts</p>
  <%end%>
  <%submodule.comments.each do |comment|%>
    <div class="single_comments"> 
      <div class="comment_user"><u><%=comment.comment_owner%></u> says </div>
      <div class="comment_content"><%=comment.content%> </div>
    </div>
    <br>
  <%end%>
  <br>
  <%=link_to("Edit submodule",edit_submodule_path(submodule),:class=>"btn btn-info")%>
 <%=link_to("Bugs",bugs_in_submodule_path(submodule.id),:class=>"btn btn-info")%>
  <%=link_to("New comment",new_comment_for_submodule_path(submodule.id),:class=>"btn btn-success")%>
</div>
<br>
<br>

<br>
<%end%>
<%end%>
</div>

app/views/projects/submodules.js.erb
$("#submodules").html("<%= escape_javascript(render "submodules")%>");

app/views/projects/team.html.erb
<meta name="csrf-token" content=<%= form_authenticity_token %>>
<form action="/team/add" method="post">
  <input type="text" name=project[member] placeholder="Enter the team mates mail id">
  <input type="Submit" value="Add member" class="btn btn-success"/>
</form>