config/routes.rb
Rails.application.routes.draw do
  resources :hooks

  resources :bugs

  resources :comments

  resources :submodules

  resources :employees

  resources :projects

  devise_for :users
  root 'projects#index'
  get 'projects/:id/submodules/'=>"projects#submodules",:as=>"project_modules"
  get 'team/projects/:id'=>"projects#team",:as=>"project_team"
  get 'team/:id'=>"projects#fullteam",:as=>"full_team"
  post 'team/add'=>"projects#add_to_team"
  get 'submodules/projects/:id'=>"submodules#new",:as=>"new_submodule_for_project"
  get 'comments/new/:id'=>"comments#new",:as=>"new_comment_for_submodule"  
  get 'submodules/bug/:id'=>"submodules#bug",:as=>"bugs_in_submodule"
  get 'bugs/new/:submodule_id'=>"bugs#new",:as=>"new_bug_for_submodule"
  get 'projects/complete/:id'=>"projects#complete",:as=>"complete_story"
  put 'request/bugs/:submodule_id/:bug_token'=>"bugs#make_bug"
end

app/models/hook.rb
class Hook < ActiveRecord::Base
  validate :purpose,presence:true
  validate :token,presence:true
  validate :name,presence:true
end

app/controllers/hooks_controller.rb
class HooksController < ApplicationController
  before_action :set_hook, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    if user_signed_in?
    @hooks = Hook.all
    respond_with(@hooks)
    else
      redirect_to new_user_session_path
    end
  end

  def show
    respond_with(@hook)
  end

  def new
    if user_signed_in?
      @hook = Hook.new
      @hook.token=Digest::SHA1.hexdigest ("#{Time.now}")
      puts Hash.new(Time.now)
      respond_with(@hook)
    else
      redirect_to new_user_session_path
    end
  end

  def edit
  end

  def create
    @hook = Hook.new(hook_params)
    @hook.save
    respond_with(@hook)
  end

  def update
    @hook.update(hook_params)
    respond_with(@hook)
  end

  def destroy
    @hook.destroy
    respond_with(@hook)
  end

  private
    def set_hook
      if user_signed_in?
        @hook = Hook.find(params[:id])
      else
        redirect_to new_user_session_path
      end
    end

    def hook_params
      params.require(:hook).permit(:name, :token, :purpose,:submodule_id)
    end
end

app/helpers/hooks_helper.rb
module HooksHelper
end

app/views/hooks/_form.html.erb
<%= form_for(@hook) do |f| %>
  <% if @hook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hook.errors.count, "error") %> prohibited this hook from being saved:</h2>

      <ul>
      <% @hook.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :name,:class=>"input-md form-control",:placeholder=>"Name for the hook" %>
  </div>
  <div class="form-group">
    <%= f.text_field :token,:class=>"input-md form-control",:disabled=>"true" %>
  </div>
  <div class="form-group">
    <%= f.select(:submodule_id, Submodule.all.collect {|a| [a.name, a.id]},{},{:class=>"form-control input-md"})%>
  </div>

  <div class="form-group">
    <%= f.select( :purpose,options_for_select(["bugs","comments"]),:class=>"input-md form-control") %>
  </div>
  <div class="actions">
  <button type="submit" class="btn btn-success">
    <i class="fa fa-save"></i> Save
  </button>
  <a href="/" class="btn btn-danger"><i class="fa fa-trash-o"></i> Cancel</a>
  </div>
<% end %>

app/views/hooks/edit.html.erb
<h1>Editing hook</h1>

<%= render 'form' %>

<%= link_to 'Show', @hook %> |

app/views/hooks/index.html.erb
<%= link_to new_hook_path ,:class=>"btn btn-primary pull-right" do%>
  <i class="fa fa-plus"></i>  New Hook
<%end%>
<h1>Hooks</h1>
<div class="row">
    <% @hooks.each do |hook| %>
    <div class="col-md-12">
      <div class="col-md-4"><div class="name"><%= hook.name %></div> <br>
        <b>URL</b> <%="request/"+hook.purpose+"/"+hook.submodule_id.to_s+"/"+hook.token%><br>
      <%= link_to 'Destroy', hook, method: :delete, data: { confirm: 'Are you sure?' } %></div>
    </div>
    <br>
    <% end %>

<br>
</div>
</div>

app/views/hooks/new.html.erb
<h1>New hook</h1>

<%= render 'form' %>

app/views/hooks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hook.name %>
</p>

<p>
  <strong>Token:</strong>
  <%= @hook.token %>
</p>

<p>
  <strong>Purpose:</strong>
  <%= @hook.purpose %>
</p>

<%= link_to 'Edit', edit_hook_path(@hook) %> |
<%= link_to 'Back', hooks_path %>