config/routes.rb
Rails.application.routes.draw do
  resources :hooks

  resources :bugs

  resources :comments

  resources :submodules

  resources :employees

  resources :projects

  devise_for :users
  root 'projects#index'
  get 'projects/:id/submodules/'=>"projects#submodules",:as=>"project_modules"
  get 'team/projects/:id'=>"projects#team",:as=>"project_team"
  get 'team/:id'=>"projects#fullteam",:as=>"full_team"
  post 'team/add'=>"projects#add_to_team"
  get 'submodules/projects/:id'=>"submodules#new",:as=>"new_submodule_for_project"
  get 'comments/new/:id'=>"comments#new",:as=>"new_comment_for_submodule"  
  get 'submodules/bug/:id'=>"submodules#bug",:as=>"bugs_in_submodule"
  get 'bugs/new/:submodule_id'=>"bugs#new",:as=>"new_bug_for_submodule"
  get 'projects/complete/:id'=>"projects#complete",:as=>"complete_story"
  put 'request/bugs/:submodule_id/:bug_token'=>"bugs#make_bug"
end

app/models/submodule.rb
class Submodule < ActiveRecord::Base
  has_many:comments
  has_many :bugs
  belongs_to :projects
  validates :name,presence:true
  validates :desc,presence:true
  validates :deadline,presence:true
  validates :score,presence:true
end

app/controllers/submodules_controller.rb
class SubmodulesController < ApplicationController
  before_action :set_submodule, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
  if user_signed_in?
    @submodules = Submodule.all
    respond_with(@submodules)
  else
    redirect_to new_user_session_path
  end
  end

  def show
    respond_with(@submodule)
  end

  def new
    @submodule = Submodule.new
    @@project_id=params[:id]
    respond_to do |format|
      format.html
      format.js
    end

  end

  def edit
  end

  def create
    @submodule = Submodule.new(submodule_params)
    @submodule.project_id=@@project_id
    if @submodule.save
      redirect_to root_path
    else
      respond_with(@submodule)
    end
  end

  def update
    if @submodule.update(submodule_params)
      redirect_to root_path
    else
      respond_with(@submodule)
    end
  end

  def destroy
    @submodule.destroy
    respond_with(@submodule)
  end
  def bug
    @submodule=Submodule.find(params[:id])
    @bugs=Bug.where(:submodule_id=>params[:id])
    respond_to do |format|
      format.html
      format.js
    end

  end
  private
    def set_submodule
    if user_signed_in?
      @submodule = Submodule.find(params[:id])
    else
      redirect_to new_user_session_path
    end
    end

    def submodule_params
      params.require(:submodule).permit(:name, :desc, :deadline, :score,:project_id,:close)
    end
end

app/helpers/submodules_helper.rb
module SubmodulesHelper
end

app/views/submodules/_bugs.html.erb
<br>
<div class="row">
  <%=link_to new_bug_for_submodule_path(@submodule.id),:class=>"btn btn-info pull-right",:remote=>true do%>
    <i class="fa fa-plus-circle"></i> New bug
    <%end%>
</div>
<%if @bugs.count==0%>

  <div class="row">
    <p class="warn">No bugs for <%=@submodule.name%></p>
  </div>
<%else%>
  <div class="bug_name"> <i class="fa fa-list"></i> Bugs for <%=@submodule.name%> </div>
  <p>Read as <strong>"Bug name"</strong> with <strong>"Bug description"</strong> is assigned to <strong>"Bug person"</strong>and the status <strong>Bug status</strong></p>

  <%@bugs.each do |bug|%>
    <%if bug.status=="open"%>
      <div class="bugs alert alert-danger">   
      <%elsif bug.status="on hold"%>
        <div class="bugs alert alert-info">
        <%elsif bug.status="working"%>
          <div class="bugs alert alert-warning">
          <%elsif bug.status=="close"%>
            <div class="bugs alert alert-success">
            <%end%>

            <%=bug.name%> <i class="fa fa-chevron-right"></i>
            <%=bug.desc.html_safe%> <i class="fa fa-chevron-right"></i>
            <%=bug.assigned_to%> <i class="fa fa-chevron-right"></i>
            <%=bug.status%>  
            <%=link_to edit_bug_path(bug),:remote=>"true",:class=>"btn btn-primary" do%>
              <i class="fa fa-edit"></i> Edit
          <%end%>

          </div>

        <%end%>
      <%end%>

app/views/submodules/_form.html.erb
<%= form_for(@submodule) do |f| %>
  <% if @submodule.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger"><%= pluralize(@submodule.errors.count, "error") %> prohibited this submodule from being saved:

      <ul>
      <% @submodule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_area :name,:class=>"form-control input-md" %>
  </div>
  <div class="form-group">

    <%= f.label :desc %><br>
    <%= f.text_area :desc,:class=>"form-control input-md",:id=>"desc" %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.datetime_select :deadline %>
  </div>
  <div class="form-group">
    <%= f.label :score %><br>
    <%= f.number_field :score,:class=>"form-control input-md" %>
  </div>
    <div class="field">
    Close <%= f.check_box :close %>
  </div>
<div class="actions">
    <input type="submit" value="Save" class="btn btn-success">
    <a href="/" class="btn btn-danger">Cancel</a>
  </div>
<% end %>
<script>
$('document').ready(function(){
    $('#desc').jqte()
    })
</script>

app/views/submodules/bug.html.erb
<div class="row">
  <%=link_to("New bug",new_bug_for_submodule_path(@submodule.id),:class=>"btn btn-info pull-right")%>
</div>
<%if @bugs.count==0%>

  <div class="row">
    <p class="warn">No bugs for <%=@submodule.name%></p>
  </div>
<%else%>
  <div class="row">
    <div class="bug_name">Bugs for <%=@submodule.name%> </div>
    <p>Read as <strong>"Bug name"</strong> with <strong>"Bug description"</strong> is assigned to <strong>"Bug person"</strong></p>

  <%@bugs.each do |bug|%>
    <div class="col-md-12">
      <div class="bugs"><%=bug.name%> <i class="fa fa-chevron-right"></i>
        <%=bug.desc%> <i class="fa fa-chevron-right"></i>
<%=bug.assigned_to%></div>
    </div>
  <%end%>
</div>
<%end%>

app/views/submodules/bug.js.erb
$("#ajaxarea").html(" ")
$("#submodules").html("<%= escape_javascript(render "bugs")%>");

app/views/submodules/edit.html.erb
<h1>Editing submodule</h1>

<%= render 'form' %>

<%= link_to 'Show', @submodule %> |

app/views/submodules/index.html.erb
<h1>Listing submodules</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th>Deadline</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @submodules.each do |submodule| %>
      <tr>
        <td><%= submodule.name %></td>
        <td><%= submodule.desc %></td>
        <td><%= submodule.deadline %></td>
        <td><%= submodule.score %></td>
        <td><%= link_to 'Show', submodule %></td>
        <td><%= link_to 'Edit', edit_submodule_path(submodule) %></td>
        <td><%= link_to 'Destroy', submodule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Submodule', new_submodule_path %>

app/views/submodules/new.html.erb
<h3>Add submodule</h3>

<%= render 'form' %>

app/views/submodules/new.js.erb
$("#ajaxarea").html("<%= escape_javascript(render(:partial =>"form"))%>");

app/views/submodules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @submodule.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @submodule.desc %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @submodule.deadline %>
</p>

<p>
  <strong>Score:</strong>
  <%= @submodule.score %>
</p>

<%= link_to 'Edit', edit_submodule_path(@submodule) %> |
<%= link_to 'Back', submodules_path %>